apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
spec:
  replicas: 2   # pods deployed on each worker node (horizontal scaling)
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080 # This is the port that the container listens on and Flask app runs on
      imagePullSecrets:
        {{- toYaml .Values.image.PullSecrets | nindent 8 }}