name: CI of the app itself; CD on KinD will be managed through GitOps with argoCD

on:
  push:
      path: 
        - 'app/**' # triggers the workflow when the app folder code is recurively changed
      branches:
        - main

permissions: # github actions permissions to access the repository and the registry
    contents: read
    packages: write

env:
    Registry: ghcr.io
    ImageRepo: memor24/my_images_dir

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: checkout the code
          uses: actions/checkout@v2

        - name: login to the GHCR
          uses: docker/login-action@v2
            with:
                registry: ${{ env.Registry }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHHUB_TOKEN }}

        - name: build the image
          run: |
            docker build -t $Registry/$ImageRepo:$GITHUB_SHA .
            docker push $Registry/$ImageRepo:GITHUB_SHA

        