apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-application
  namespace: argocd      
spec:
  project: default
  source:
    repoURL: https://github.com/memor24/kuber-argocd-gitops.git
    path: app                                       # path to what we want to sync e.g. app git repo
    targetRevision: HEAD                            # Git branch, tag, or commit SHA
  destination:
    server: https://kubernetes.default.svc          ## to: app-cluster external url if any
    namespace: my-app-ns                            # namespace to deploy the app
  syncPolicy:
    automated:
      prune: true                                   # deletes resources not in Git
      selfHeal: true                                # disallows kubectl manual changes
    syncOptions:                                    
      - CreateNamespace=true                        # creates the namespace if it doesn't exist