apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    labels:
      app: my-app
    spec:
      containers:
        - name: my-app      # overrides the image, repo, tag
          image: "my-app"  
          repository: "ghcr.io/memor24/kag-imagefolder/"
          tag: {{ github.sha }}           
          pullPolicy: "Always"   # "IfNotPresent" in prod
          pullSecrets: []        # secret to pull image from private repo using regcred in ci.yml
          # ports:
          #   - containerPort: 8080
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "8192Mi"
          #     cpu: "4"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 3
          #   periodSeconds: 3