apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    labels:
      app: my-app
    spec:
      containers:
        - name: my-app
          image: ""           # overrides the image
          repository: ""
          tag: ""           
        # pullPolicy: ""
        # pullSecrets: []   # secret to pull from private repo
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "8192Mi"
              cpu: "4"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3