name: CI of the app itself; CD on KinD will be managed through GitOps with argoCD

on:
  push:
      branches:
        - main
      paths: 
        - 'app/src/**' # triggers the workflow when the app folder code is updated
workflow_dispatch: # activates manual trigger for testing

env:
    Registry: ghcr.io
    Repository: memor24/imgfolder

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:  # github actions permissions to access the repository and the registry
      contents: read
      packages: write
    steps:
        - name: Debug repository structure
          run: ls -R

        - name: checkout the code
          uses: actions/checkout@v2

        - name: login to the GHCR
          uses: docker/login-action@v2
          with:
                registry: ${{ env.Registry }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

        - name: Debug environment variables
          run: |
            echo "Registry: ${{ env.Registry }}"
            echo "Repository: ${{ env.Repository }}"
            echo "GITHUB_SHA: ${{ github.sha }}"

        - name: build & push the image with updated image tag
          uses: docker/build-push-action@v4
          with:
                context: .
                push: true
                tags: ${{ env.Registry }}/${{ env.Repository }}:${{ github.sha }}

        - name: notifying message
          run: |
            echo "ci job is completed"


        